:test:
  :threaded: true
  :timeout:  9
  :redis:
    :message:
      :host: 127.0.0.1
      :port: 6379
      :db:   2
    :admin:
      :host: 127.0.0.1
      :port: 6379
      :db:   2
    :session:
      :host: 127.0.0.1
      :port: 6379
      :db:   2
